### ISSUE TITLE
[QuakeMapFormat] System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by Charanor** [LogicAndTrick/sledge-formats#18]
When using the QuakeMapFormat class on this map file (see below) I get a `System.FormatException: Input string was not in a correct format` with the following stack trace:

```
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Decimal.Parse(String s, NumberStyles style)
   at Sledge.Formats.Map.Formats.QuakeMapFormat.ParseDecimal(IEnumerator`1 it)
   at Sledge.Formats.Map.Formats.QuakeMapFormat.ReadTextureAxis(IEnumerator`1 it)
   at Sledge.Formats.Map.Formats.QuakeMapFormat.ReadFace(IEnumerator`1 it)
   at Sledge.Formats.Map.Formats.QuakeMapFormat.ReadSolid(IEnumerator`1 it)
   at Sledge.Formats.Map.Formats.QuakeMapFormat.ReadEntity(IEnumerator`1 it)
   at Sledge.Formats.Map.Formats.QuakeMapFormat.Read(Stream stream)
```

The map file is short and simple, it is the default map with the texture replaced. The texture is the "Icon.png" file in the "Generic" game mode folder (not that it matters... probably).

The map was created using TrenchBroom and is in the "Valve" format as specified here: https://trenchbroom.github.io/manual/latest/#compiling_maps:~:text=for%20more%20information.-,File%20Formats,-The%20file%20format

```
{
"mapversion" "220"
"classname" "worldspawn"
"_tb_textures" "textures"
// brush 0
{
( -64 -64 -16 ) ( -64 -63 -16 ) ( -64 -64 -15 ) Icon [ 0 -0.9999999999999848 -1.7484556036340138e-07 0 ] [ 0 1.7484556036340138e-07 -0.9999999999999848 0 ] 360 1 1
( -64 -64 -16 ) ( -64 -64 -15 ) ( -63 -64 -16 ) Icon [ 1 0 -0 55 ] [ 0 -0 -1 64 ] 0 1 1
( -64 -64 -16 ) ( -63 -64 -16 ) ( -64 -63 -16 ) Icon [ -0.9999999999999848 -1.7484556036340138e-07 0 0 ] [ 1.7484556036340138e-07 -0.9999999999999848 0 0 ] 360 1 1
( 64 64 16 ) ( 64 65 16 ) ( 65 64 16 ) Icon [ 0.9999999999999848 -1.7484556036340138e-07 0 0 ] [ -1.7484556036340138e-07 -0.9999999999999848 0 0 ] 360 1 1
( 64 64 16 ) ( 65 64 16 ) ( 64 64 17 ) Icon [ -0.9999999999999848 0 -1.7484556036340138e-07 0 ] [ 1.7484556036340138e-07 0 -0.9999999999999848 0 ] 360 1 1
( 64 64 16 ) ( 64 64 17 ) ( 64 65 16 ) Icon [ 0 0.9999999999999848 -1.7484556036340138e-07 0 ] [ 0 -1.7484556036340138e-07 -0.9999999999999848 0 ] 360 1 1
}
}
```

**Package version:** 1.0.4 (NuGet)

**Comment by Charanor** [comment]
Figured out why at least. It's because `Decimal.Parse` takes culture into account, and since my culture uses `,` instead of `.` as decimal separator it crashes when it sees a number using `.`. This should be fixable by adding invariant culture to the parse call in `QuakeMapFormat`:
```
Decimal.Parse(..., ..., CultureInfo.InvariantCulture)
```
A fix for this would be most appreciated 🙏

**Comment by LogicAndTrick** [comment]
Thanks for checking it out, rookie mistake on my side. Will push a fix out in a little while.

**Comment by LogicAndTrick** [comment]
It should work now with version 1.0.5!
